# container-manager/Dockerfile.dev
FROM golang:1.22

WORKDIR /app

# Устанавливаем Air (hot-reload) и Delve (debugger)
RUN go install github.com/air-verse/air@latest && \
    go install github.com/go-delve/delve/cmd/dlv@latest

# Копируем go.mod и go.sum для кэширования слоев
COPY go.mod go.sum ./
RUN go mod download

# Запускаем Air (он сам подхватит конфигурацию из .air.toml)
CMD ["air", "-c", ".air.toml"]
