version: '3.8'

services:
  # Ваше управляющее Spring Boot приложение
  jelenoid-app:
    build: . # Указывает на Dockerfile в текущей папке
    container_name: jelenoid-app
    ports:
      # Пробрасываем порт вашего приложения на хост
      - "4444:4444"
      # Можно добавить порт для отладки
      - "5005:5005"
    volumes:
      # Для горячей перезагрузки[4]
      - ./src:/app/src
      - ./target:/app/target
      # Важно: пробрасываем сокет Docker, чтобы приложение могло управлять контейнерами
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      # Переменные для отладки
      #- MAVEN_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5005
      # Передаем имя сети в приложение
      - JELENOID_DOCKER_NETWORK=jelenoid-net
    # Подключаем приложение к нашей сети
    networks:
      - jelenoid-net

# Объявляем сеть
networks:
  jelenoid-net:
    name: jelenoid-net
    driver: bridge # Указываем, что сеть создана заранее