version: '3.8'

services:
  # Ваше управляющее Spring Boot приложение
  jelenoid-server:
    build: ./jelenoid-server # Указывает на Dockerfile в текущей папке
    container_name: jelenoid-server
    ports:
      # Пробрасываем порт вашего приложения на хост
      - "4444:4444"
      # Можно добавить порт для отладки
      - "5005:5005"
    volumes:
      # Для горячей перезагрузки[4]
      - ./jelenoid-server/src:/app/src
      - ./jelenoid-server/target:/app/target
      # Важно: пробрасываем сокет Docker, чтобы приложение могло управлять контейнерами
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      # Переменные для отладки
      #- MAVEN_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5005
      # Передаем имя сети в приложение
      - JELENOID_DOCKER_NETWORK=jelenoid-net
    # Подключаем приложение к нашей сети
    networks:
      - jelenoid-net
  jelenoid-ui:
    image: node:20-alpine # Используем официальный легковесный образ Node.js
    container_name: jelenoid-ui
    working_dir: /app
    volumes:
      # Монтируем наш локальный код в контейнер для live-reload
      - ./jelenoid-ui:/app
    stdin_open: true
    tty: true
    ports:
      # Пробрасываем порт Vite на нашу машину
      - "5173:5173"
    # Запускаем установку зависимостей и сервер разработки
    # Флаг --host необходим, чтобы сервер был доступен извне контейнера
    command: sh -c "npm install && npm run dev -- --host"
    networks:
      - jelenoid-net
    depends_on:
      - jelenoid-server

# Объявляем сеть
networks:
  jelenoid-net:
    name: jelenoid-net
    driver: bridge # Указываем, что сеть создана заранее