version: '3.8'

services:
  jelenoid-server:
    build: ./jelenoid-server
    container_name: jelenoid-server
    ports:
      - "4444:4444"
      - "5005:5005"
    volumes:
      - ./jelenoid-server/src:/app/src
      - ./jelenoid-server/target:/app/target
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jelenoid-net
  jelenoid-ui:
    image: node:20-alpine
    container_name: jelenoid-ui
    working_dir: /app
    volumes:
      - ./jelenoid-ui:/app
    stdin_open: true
    tty: true
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host"
    networks:
      - jelenoid-net
    depends_on:
      - jelenoid-server


networks:
  jelenoid-net:
    name: jelenoid-net
    driver: bridge