server:
  port: ${SELENOID_PORT:8080}

spring:
  application:
    name: superselenoid

superselenoid:
  browsers:
    config-dir: ${BROWSERS_FILE:}
  timeouts:
    session: ${SESSION_TIMEOUT:60000}
    startup: 10000
    cleanup: 15000

management:
  endpoint:
    health:
      show-details: always
      group:
        custom:
          include: diskSpace,docker
  endpoints:
    web:
      exposure:
        include: health,info