server:
  port: ${JELENOID_PORT:8080}

spring:
  application:
    name: jelenoid

jelenoid:
  logs:
    dir: ${LOG_OUTPUT_DIR:/logs}
  video:
    dir: ${VIDEO_OUTPUT_DIR:/videos}
    recorder-image: ${RECORDER_IMAGE:selenoid/video-recorder:latest-release}
  docker:
    network: ${DOCKER_NETWORK:jelenoid-net}
  browsers:
    config-dir: ${BROWSERS_FILE:}
  timeouts:
    session: ${SESSION_TIMEOUT:60000}
    startup: ${STARTUP_TIMEOUT:10000}
    cleanup: ${CLEANUP_TIMEOUT:15000}

management:
  endpoint:
    health:
      show-details: always
      group:
        custom:
          include: diskSpace,docker
  endpoints:
    web:
      exposure:
        include: health,info