server:
  port: ${JELENOID_PORT:4444}

spring:
  application:
    name: jelenoid

jelenoid:
  limit: ${PARALLEL_SESSIONS:5}
  queue:
    limit: ${QUEUE_LIMIT:5}
    timeout: ${QUEUE_TIMEOUT:300}
  logs:
    dir: ${LOG_OUTPUT_DIR:/logs}
  video:
    dir: ${VIDEO_OUTPUT_DIR:/videos}
    recorder-image: ${RECORDER_IMAGE:selenoid/video-recorder:latest-release}
  docker:
    network: ${DOCKER_NETWORK:jelenoid-net}
  browsers:
    config-dir: ${BROWSERS_FILE:}
  timeouts:
    session: ${SESSION_TIMEOUT:600000}
    startup: ${STARTUP_TIMEOUT:30000}
    cleanup: ${CLEANUP_TIMEOUT:15000}

management:
  endpoint:
    health:
      show-details: always
      group:
        custom:
          include: diskSpace,docker
  endpoints:
    web:
      exposure:
        include: health,info