server:
  port: ${CONTAINER_MANAGER_PORT:8080}

spring:
  threads:
    virtual:
      enabled: true
  mvc:
    async:
      request-timeout: 500000
  application:
    name: container-manager

jelenoid:
  docker:
    network: ${DOCKER_NETWORK:jelenoid-net}
  timeouts:
    cleanup: ${CLEANUP_TIMEOUT:15000}
    starting_timeout: ${CONTAINER_STARTING_TIMEOUT:60000}