server:
  port: ${JELENOID_PORT:4444}

spring:
  threads:
    virtual:
      enabled: true
  mvc:
    async:
      request-timeout: 500000
  application:
    name: jelenoid

jelenoid:
  container-manager:
    address: ${CONTAINER_MANAGER_ADDRESS:http://localhost:8080}
  limit: ${PARALLEL_SESSIONS:10}
  queue:
    limit: ${QUEUE_LIMIT:100}
  browsers:
    config-dir: ${BROWSERS_FILE:browsers.json}
  timeouts:
    queue: ${QUEUE_TIMEOUT:30000}
    session: ${SESSION_TIMEOUT:600000}
    startup: ${STARTUP_TIMEOUT:30000}
  ui_hosts: ${UI_HOSTS_LIST:http://localhost:3000,http://localhost:4444}
  playwright:
    port: ${PLAYWRIGHT_PORT:3000}
    default_version: ${PLAYWRIGHT_DEFAULT_VERSION:1.53.0}
    max_sessions: ${PLAYWRIGHT_SESSION_LIMIT:10}
    queue_limit: ${PLAYWRIGHT_QUEUE_LIMIT:100}
  nats-server: ${NATS_SERVER:}

management:
  endpoint:
    health:
      show-details: always
      group:
        custom:
          include: diskSpace
  endpoints:
    web:
      exposure:
        include: health,info