server:
  port: ${JELENOID_PORT:4444}

spring:
  mvc:
    async:
      request-timeout: 500000
  application:
    name: jelenoid

jelenoid:
  limit: ${PARALLEL_SESSIONS:10}
  queue:
    limit: ${QUEUE_LIMIT:100}
  logs:
    dir: ${LOG_OUTPUT_DIR:/logs}
  video:
    dir: ${VIDEO_OUTPUT_DIR:/videos}
    recorder-image: ${RECORDER_IMAGE:selenoid/video-recorder:latest-release}
  docker:
    network: ${DOCKER_NETWORK:jelenoid-net}
  browsers:
    config-dir: ${BROWSERS_FILE:}
  timeouts:
    queue: ${QUEUE_TIMEOUT:30000}
    session: ${SESSION_TIMEOUT:600000}
    startup: ${STARTUP_TIMEOUT:30000}
    cleanup: ${CLEANUP_TIMEOUT:15000}
  executor:
    core-pool-size: ${EXECUTOR_POOL_SIZE:5}
    max-pool-size: ${EXECXUTOR_MAX_POOL_SIZE:10}
    queue-capacity: ${EXECUTOR_QUEUE_CAPACITY:100}
  ui_hosts: ${UI_HOSTS_LIST:http://localhost:3000,http://localhost:4444}
  playwright:
    port: ${PLAYWRIGHT_PORT:3000}
    default_version: ${PLAYWRIGHT_DEFAULT_VERSION:1.53.1}
    max_sessions: ${PLAYWRIGHT_SESSION_LIMIT:10}
    queue_limit: ${PLAYWRIGHT_QUEUE_LIMIT:100}

management:
  endpoint:
    health:
      show-details: always
      group:
        custom:
          include: diskSpace,docker
  endpoints:
    web:
      exposure:
        include: health,info